#!/bin/bash  
move3d-qt-studio -setgui -params ../move3d-launch/parameters/params_human_robot_example -c pqp -f ../assets/Gesture/HumanPR2Example.p3d -sc ../../move3d/assets/Gesture/SCENARIOS/HumanRobotExample.sce 
#-sc ../../move3d/assets/Gesture/SCENARIOS/PR2TwoCupsSideParallel.sce
# -launch PredictionSimulation 
# valgrind --tool=memcheck --leak-check=full --error-limit=no 
