#!/bin/bash  
move3d-qt-studio -launch PredictionSimulation -setgui -params ../move3d-launch/parameters/params_pipeline_two_cups -c pqp -f ../assets/Gesture/HumanPR2TwoCups.p3d -sc ../../move3d/assets/Gesture/SCENARIOS/PR2TwoCupsFacing.sce
# -launch PredictionSimulation
